spring:
  application:
    name: Budget_manager

  profiles:
    active: postgres

  config:
    activate:
          on-profile: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/bmdb
    username: bm
    password: bm

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration, 
               classpath:db/local/migration

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

app:
  security:
    jwt:
      secret: "sec"

    cookies:
      secure: true
      sameSite: "Lax"

    refresh:
      revoke-detect: true

      cleanup:
        enabled: true
        retention: P7D
        cron: "0 0 4 * * *"

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    withCredentials: true

